# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd9a5bb0d9b2b0f6965fc899c56bc62ab8c16292e732ed09a421b5f214ab9b26773e5a970beca96b36eedd219679851896b75a5ee927a0bc5fb86094e98f0ac5

test:
  secret_key_base: 3f29356e4321b01b610a3bb2ee7a68532d5fb481cb8c493e76e7971439a6e3ffcd4c37133d62c7014bc77ea878c859c864a0da1cfb715e068ba348d061d97d69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
